# Generated by Django 5.2.5 on 2025-08-21 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttestationNotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attested_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('attested_by_position', models.CharField(blank=True, max_length=100, null=True)),
                ('attested_by_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('noted_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('noted_by_position', models.CharField(blank=True, max_length=100, null=True)),
                ('noted_by_signature', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeasedPropertyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('proponent_name', models.CharField(max_length=255)),
                ('contact_no', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('lot_status', models.CharField(blank=True, max_length=100, null=True)),
                ('land_classification_status', models.CharField(blank=True, max_length=100, null=True)),
                ('title_no', models.IntegerField(blank=True, null=True)),
                ('lot_no', models.IntegerField(blank=True, null=True)),
                ('lot_owner', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('area_covered', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pa_management_zone', models.CharField(blank=True, max_length=100, null=True)),
                ('establishment_status', models.CharField(blank=True, max_length=100, null=True)),
                ('easement', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PermitsDENREMB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pamb_resolution', models.BooleanField(default=False)),
                ('pamb_resolution_no', models.IntegerField(blank=True, null=True)),
                ('pamb_di', models.DateField(blank=True, null=True)),
                ('sapa', models.BooleanField(default=False)),
                ('sapa_no', models.IntegerField(blank=True, null=True)),
                ('sapa_di', models.DateField(blank=True, null=True)),
                ('pacbrma', models.BooleanField(default=False)),
                ('pacbrma_no', models.IntegerField(blank=True, null=True)),
                ('pacbrma_di', models.DateField(blank=True, null=True)),
                ('ecc', models.BooleanField(default=False)),
                ('ecc_no', models.IntegerField(blank=True, null=True)),
                ('ecc_di', models.DateField(blank=True, null=True)),
                ('discharge_permit', models.BooleanField(default=False)),
                ('dp_no', models.IntegerField(blank=True, null=True)),
                ('dp_di', models.DateField(blank=True, null=True)),
                ('permit_to_operate', models.BooleanField(default=False)),
                ('pto_no', models.IntegerField(blank=True, null=True)),
                ('pto_di', models.DateField(blank=True, null=True)),
                ('emb_rp', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PermitsLGU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mayors_permit', models.BooleanField(default=False)),
                ('mp_number', models.IntegerField(blank=True, null=True)),
                ('mpdi', models.DateField(blank=True, null=True)),
                ('mped', models.DateField(blank=True, null=True)),
                ('business_permit', models.BooleanField(default=False)),
                ('bp_number', models.IntegerField(blank=True, null=True)),
                ('bpdi', models.DateField(blank=True, null=True)),
                ('bped', models.DateField(blank=True, null=True)),
                ('building_permit', models.BooleanField(default=False)),
                ('bldg_number', models.IntegerField(blank=True, null=True)),
                ('bldgdi', models.DateField(blank=True, null=True)),
                ('bldged', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProtectedArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfEstablishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('region', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('Super Admin', 'Super Admin'), ('Admin', 'Admin'), ('PENRO', 'Penro'), ('CENRO', 'Cenro'), ('Evaluator', 'Evaluator')], max_length=20)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('profile_pic', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeoTaggedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=255)),
                ('qr_code', models.CharField(max_length=255, unique=True)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('location', models.CharField(max_length=255)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('captured_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captured_images', to='DENRO.user')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluatorsTrackRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pointer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DENRO.geotaggedimage')),
                ('captured_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DENRO.user')),
            ],
        ),
        migrations.CreateModel(
            name='EnumeratorsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('attestation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DENRO.attestationnotation')),
                ('geo_tag_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DENRO.geotaggedimage')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DENRO.leasedpropertyprofile')),
                ('denr_emb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DENRO.permitsdenremb')),
                ('lgu_permit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DENRO.permitslgu')),
                ('pa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DENRO.protectedarea')),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DENRO.typeofestablishment')),
                ('enumerator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enumerator_reports', to='DENRO.user')),
                ('informant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informant_reports', to='DENRO.user')),
            ],
        ),
    ]
