# Generated by Django 5.2.5 on 2025-08-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DENRO", "0002_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
