# Generated by Django 5.2.5 on 2025-09-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DENRO', '0006_user_is_deactivated_user_is_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('ERROR', 'Error'), ('REPORT_CENRO', 'CENRO Report'), ('REPORT_PENRO', 'PENRO Report')], max_length=16),
        ),
    ]
