# Generated by Django 5.2.5 on 2025-09-04 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DENRO', '0007_user_id_number_alter_activitylog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='enumeratorsreport',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined')], default='PENDING', max_length=10),
        ),
    ]
