# Generated by Django 5.2.5 on 2025-09-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DENRO', '0008_enumeratorsreport_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
    ]
