# Generated by Django 5.2.5 on 2025-09-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DENRO', '0009_activitylog_latitude_activitylog_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
